// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

const push = true

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: push ? env("DIRECT_URL") : env("DATABASE_URL"),
    shadowDatabaseUrl: push ? env("DATABASE_URL") : env("DIRECT_URL"),
  },
});
